name: ci

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.github/**'

permissions:
    contents: write    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - 
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: '0'
  
      -
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - 
        name: Test with the Go CLI
        run: go test -v
  
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: tag
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: true
            RELEASE_BRANCHES: main
  
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ntse/export-php-metrics:${{ steps.tag.outputs.new_tag }}, ntse/export-php-metrics:latest
