name: "[Workflow] PR Environment"

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write


jobs: 

  foo:
    name: "Foo"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: "ministryofjustice/opg-github-actions"
          ref: "5adf4178379b79db1d0a463833badde786401a03"
          path: "opg-github-actions"
      - name: semver tag
        id: semver_tag
        uses: ./opg-github-actions/.github/actions/semver-tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          with_v: true
